name: widget_template_language
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular
description: Parser and utilities for flutter widget templates
version: 0.0.1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  charcode: ^1.1.0
  collection: ^1.14.5
  string_scanner: ^1.0.1
  meta: ^1.1.4
  source_span: ^1.4.0
  build: ^1.1.1

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2+5
  path: ^1.6.1
  test: ^1.3.0
